Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/focal64"
    config.vm.box_check_update = false
    config.vm.provider "virtualbox" do |vb|
       vb.gui = false
       vb.name = "ubuntu2004"
       vb.cpus = "2"
       vb.memory = "1024"
    end
    
  end
  
 